### ISSUE TITLE
Allow to keep indices in the OCaml code

### ISSUE THREAD

**Issue by Drup** [lukstafi/invargent#2]
I'm not sure how easy it is, but in this code example: 

``` ocaml
datatype List : type * num
datacons LNil : ∀a. List(a, 0)
datacons LCons : ∀n, a. a * List(a, n) ⟶ List(a, n+1)

datatype Term : num
datacons Add : all n, m. Term n * Term m --> Term (n+m)
datacons Var : Term 1
datacons Val : Float --> Term 0

external plusF : Float -> Float -> Float

let rec eval = function
  | l, Val i -> (l,i)
  | LCons (x,xs), Var -> (xs, x)
  | l,Add(t1, t2) ->
    let (l', i1) = eval (l, t1) in
    let (l'', i2) = eval (l', t2) in
    (l'', plusF i1 i2)
```

ocaml (rightfully) complains about a non-exhaustive pattern matching and the function become pretty much pointless without the type indices ...

**Comment by lukstafi** [comment]
OCaml does not rightfully complain here. The pattern matching is exhaustive from the point of view of InvarGenT because `LNil` cannot be paired with `Var` . `LNil` means that "n + k = 0", `Var` means that "k = 1", and "n >= 0" by definition of the "List" datatype above. That being said, unfortunately at this point InvarGenT does not track nor ensure exhaustiveness...

**Comment by Drup** [comment]
I mean "rightfully" from OCaml's point of view where num have been erased.

**Comment by lukstafi** [comment]
Yes, of course OCaml works correctly. The exhaustiveness in this example assumes that the uses respect the inferred type. A cool idea would be to, optionally, re-parse OCaml's warning and add a pattern matching branch with `assert false` on the right hand side. This would give us an exhaustiveness guarantee on InvarGenT side. We cannot guarantee correctness of uses on the OCaml side anyway without some additional R&D (exporting as a module with abstract types?) because the types in OCaml are weaker (i.e. more general).

**Comment by lukstafi** [comment]
We cannot keep `num` indices in OCaml code -- OCaml does not have type constraints in the numerical domain.

**Comment by lukstafi** [comment]
Unfortunately, my proposed solution:

```
let rec eval = function
  | l, Val i -> (l,i)
  | LNil, Var -> assert false
  | LCons (x,xs), Var -> (xs, x)
  | l,Add(t1, t2) ->
    let (l', i1) = eval (l, t1) in
    let (l'', i2) = eval (l', t2) in
    (l'', plusF i1 i2)
```

fails at present. I will add this to the test suite to get fixed. Note that one would use it as follows:

```
./invargent -inform -keep_assert_false examples/issue2.gadt
```

**Comment by lukstafi** [comment]
The failure to infer with the above definitions is correct. It is because the formalism behind InvarGenT treats the variant types as extensible, see [OCaml Manual 7.26: Extensible variant types](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec246). The correct implementation is as follows: let `examples/issue2.gadt` be

```
datatype List : type * num
datacons LNil : ∀a. List(a, 0)
datacons LCons : ∀n, a [0≤n]. a * List(a, n) ⟶ List(a, n+1)

datatype Term : num
datacons Add : ∀n, m [0≤n ∧ 0≤m]. Term n * Term m --> Term (n+m)
datacons Var : Term 1
datacons Val : Float --> Term 0

external plusF : Float -> Float -> Float

let rec eval = function
  | l, Val i -> (l,i)
  | LNil, Var -> assert false
  | LCons (x,xs), Var -> (xs, x)
  | l,Add(t1, t2) ->
    let (l', i1) = eval (l, t1) in
    let (l'', i2) = eval (l', t2) in
    (l'', plusF i1 i2)
```

Then the invocation looks like this:

```
$ ./invargent -inform -keep_assert_false examples/issue2.gadt
val eval :
  ∀k, n[0 ≤ n].
  (List (Float, n + k), Term k) → (List (Float, n), Float)
InvarGenT: Generated file examples/issue2.gadti
InvarGenT: Generated file examples/issue2.ml
InvarGenT: Command "ocamlc -w -25 -c examples/issue2.ml" exited with code 0
```

A slight change to negation handling was required: we now infer the `-keep_assert_false` case differently, not trying to include the negated constraint right away, but waiting one iteration to see if it will get contradicted. It's in the most recent commit.

**Comment by Drup** [comment]
I see. invargent note that the `assert false` is not accessible here ? I wonder if a special syntax for unreachable cases like Agda's one would be a good thing.

**Comment by lukstafi** [comment]
Yes, `assert false` in InvarGenT means that the code is _statically_ not accessible. You can use the keyword `runtime_failure` for the branch that is _dynamically_ supposed to not be accessible.

**Comment by lukstafi** [comment]
In other words, `assert false` **is** the special syntax for unreachable cases.

**Comment by Drup** [comment]
This is not intuitive for ocamlers. :D

**Comment by lukstafi** [comment]
Logically speaking, `assert false` sounds like contradiction. Other uses of `assert` are also static in `InvarGenT` -- `assert type t1 = t2` enforces the _types_ of `t1` and `t2` be equal, `assert num n1 <= n2` statically enforces that `n1` is smaller than `n2`.

**Comment by Drup** [comment]
I'm not saying it's not logical/consistent, just not intuitive. ;)
